const URLbs = 'http//192.168.118.133:8000/api/'

export const environment ={
  production : false,
  index : `${URLbs}users/index`,
  store: `${URLbs}store`,
  login: `${URLbs}login`,
  logout: `${URLbs}logout`,
  update: `${URLbs}update`,
  delete: `${URLbs}delete/`,
  show: `${URLbs}show/`,
  see : `${URLbs}sse-updates`,
  authenticate: `${URLbs}authenticatetoken`,
  adminAuth: `${URLbs}adminauth`,
  userAuth: `${URLbs}userauth`,
  Sse : `${URLbs}services/sse`,
  guestAuth: `${URLbs}guestauth`,
  speciesIndex: `${URLbs}specie/index`,
  petStore: `${URLbs}pet/store`,
  specieStore: `${URLbs}specie/store`,
  productIndex: `${URLbs}product/index`,
  getPetsByUser: `${URLbs}pet/index/`,
  storeAppointment: `${URLbs}vetappointment/store`,
  indexAppointments: `${URLbs}vetappointment/index`,
  markAppointmentAsCompleted: `${URLbs}vetappointment/complete/`,
  cancelledAppointments: `${URLbs}vetappointment/canceled/index`,
  reOpenAppointment: `${URLbs}vetappointment/reopen/`,
  markAppointmentAsCancelled: `${URLbs}vetappointment/reject/`,
  categoriesIndex: `${URLbs}category/index`,
  categoriesDestroy: `${URLbs}category/destroy/`,
  getCategoryId: `${URLbs}category/getCategory/`,
  updateCategory: `${URLbs}category/update/`,
  categoryActivate: `${URLbs}category/activate/`,
  categoriesDisabled: `${URLbs}category/index/desactivated`,
  storeCategories: `${URLbs}category/store`,
  productStore: `${URLbs}product/store`,
  prescriptionStore: `${URLbs}vetprescription/store`,
  productModify: `${URLbs}product/update/`,
  showProductId: `${URLbs}product/show/`,
  deleteProduct: `${URLbs}product/delete/`,
  userPets: `${URLbs}pet/userpets/`,
  prescriptionsIndex: `${URLbs}vetprescription/index`,
  userPrescriptionsIndex: `${URLbs}vetprescription/user/`,
  getVetAppointmentsByUser: `${URLbs}vetappointment/user/`,
  completedAppointments: `${URLbs}vetappointment/completed/index`,
  desactivateUser: `${URLbs}users/desactivate/`,
  showPet: `${URLbs}pet/show/`,
  updatePet: `${URLbs}pet/update/`,
  petIndex: `${URLbs}pet/activatedPets`,
  deactivatedPetIndex: `${URLbs}pet/deactivatedPets`,
  activePets: `${URLbs}pet/active/name/`,
  deactivatedPets: `${URLbs}pet/deactivated/name/`,
  activatePet: `${URLbs}pet/activate/`,
  deactivatePet: `${URLbs}pet/delete/`,
  specieDeactivatedIndex: `${URLbs}specie/deactivated/index`,
  activateSpecie: `${URLbs}specie/activate/`,
  deactivateSpecie: `${URLbs}specie/delete/`,
  activeSpecies: `${URLbs}specie/active/name/`,
  deactivatedSpecies: `${URLbs}specie/deactivated/name/`,
  updateSpecie: `${URLbs}specie/update/`,
  showSpecie: `${URLbs}specie/show/`,
  changerol: `${URLbs}users/changerole/`,
  totalAppointments: `${URLbs}vetappointment/totalApointments`,
  totalUsuarios: `${URLbs}users/totalUsers`,
  totalProductos: `${URLbs}product/totalProducts`,
  logsindex: `${URLbs}users/logsindex`,
  logsmethod: `${URLbs}users/logsmethod/`,
  loguser: `${URLbs}users/xid/`,
  productsStockBajo: `${URLbs}product/stockBajo`,
  AppointmentUser: `${URLbs}vetappointment/info/Appointments`,
  findAppointmentByName: `${URLbs}vetappointment/find/name/`,
  findCancelledAppointmentByName: `${URLbs}vetappointment/find/cancelled/name/`,
  findCompletedAppointmentByName: `${URLbs}vetappointment/find/completed/name/`,
  findPrescriptionByName: `${URLbs}vetprescription/find/name/`,
  salesIndex: `${URLbs}product/ventas/index`,
  productsDisabled: `${URLbs}products/index/disabled`,
  enableProd: `${URLbs}products/activate/`,
  findUserPetByName: `${URLbs}pet/find/name/`,
  findUserAppointmentsByDate: `${URLbs}vetappointment/find/date/`,
  findUSerPrescriptionsByDate: `${URLbs}vetprescription/find/date/`,
  serviceindex: `${URLbs}services/index`,
  servicestore: `${URLbs}services/store`,
  servicemodify: `${URLbs}services/update/`,
  serviceshow: `${URLbs}services/show/`,
  servicedelete: `${URLbs}services/destroy/`,
  getTotal: `${URLbs}product/getTotal`,
  makeSale: `${URLbs}product/venta`,
  getProductSearch: `${URLbs}product/getProduct/`,
  logsMethodGet: `${URLbs}users/logsMethodGet`,
  logsMethodPost: `${URLbs}users/logsMethodPost`,
  logsMethodPut: `${URLbs}users/logsMethodPut`,
  logsMethodDelete: `${URLbs}users/logsMethodDelete`,
  logsByName: `${URLbs}users/logsByName/`,
  cleanlogs: `${URLbs}users/cleanlogs`,

  pusher: {
    key: `2489eced27769e3a01d1`,
    cluster: `us3`
  }
}
